apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: demo
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 5s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'cheezer-webhook'
    receivers:
    - name: 'cheezer-webhook'
      webhook_configs:
      - url: 'http://cheezer-core.demo.svc.cluster.local:9090/api/grafana_webhook'
        send_resolved: false
        http_config:
          bearer_token: 'hackathon2026'
        headers:
          x-api-key: 'hackathon2026'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-alertmanager
  namespace: demo
  labels:
    app: grafana-alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-alertmanager
  template:
    metadata:
      labels:
        app: grafana-alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.27.0
        args:
          - "--config.file=/etc/alertmanager/alertmanager.yml"
          - "--storage.path=/alertmanager"
        ports:
          - containerPort: 9093
            name: http
        volumeMounts:
          - name: config-volume
            mountPath: /etc/alertmanager
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager-config
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-alertmanager
  namespace: demo
spec:
  selector:
    app: grafana-alertmanager
  ports:
    - port: 9093
      targetPort: 9093
      name: http
