[package]
name = "cheezer-core"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.9"
env_logger = "0.11.11"
k8s-openapi = { version = "0.28.0", features = ["latest"] }
kube = { version = "4.2.0", features = ["runtime"] }
log = "0.4.34"
reqwest = { version = "0.13.4", features = ["json"] }
rusqlite = { version = "0.40.2", features = ["bundled"] }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
base64 = "0.22"
chrono = "0.4"
futures = "0.3"


[dev-dependencies]
wiremock = "0.6.5"
